### PR TITLE
Preserve newlines and normalize whitespace

### PR DESCRIPTION
**Pull request by cubedhuang**
This PR changes fetching from `tsv` files to `csv` files which preserve original whitespace better. Python has a builtin `csv` module which is pretty convenient

Output in `data.json` is changed by preserving newlines and normalizing some other whitespace (i.e. removing double spaces and removing spaces at the start and end of strings).

### CODE REVIEW

**Comment by cubedhuang** [comment]
oh yeah some formatting stuff is changed cuz i have black formatter installed for python which adjusted some stuff

**Comment by neverabsolute** [comment]
double quotes in py 👎

**Comment by cubedhuang** [comment]
> double quotes in py 👎

i am a faithful double quote user

**Comment by gregdan3** [comment]
Python Black is my preferred formatter, because I don't want to think about formatting, so all good by me. 

Statement duplicated from the server:

Nice change! Makes me think we should include some tests to assert the structure of jasima, in case of sheet vandalism or changes like these which appear benign but run the very real risk of having breaking changes (particularly your whitespace normalizer, though I can't think of anything wrong with it in any case).

[you also showed a diff with only very minor changes so :+1: to this]

**Pull request merged**
